Changed the device tree to use framebuffer write
topic-embedded-products/meta-topic pull request #17
Opened 2020-09-21 13:47 UTC by gijsvesch

The first camera will now go via the framebuffer write again and not via dyplo

2020-09-21 13:53 UTC, MikeLooijmans commented
Missing: FPGA image
Merging this will break things.

2020-09-21 13:55 UTC, MikeLooijmans requested changes
Missing: FPGA image
Merging this will break things.

2020-10-29 07:18 UTC, gijsvesch commented
Added an extra BB append file to now use the correct FPGA image

2020-10-29 09:29 UTC, gijsvesch commented
Updated and squashed the commits

2020-10-29 09:50 UTC, MikeLooijmans commented
Alleen nog de commit tekst aanpassen. Wat verandert er, voor welk bord en waarom.
Kijk naar andere commit teksten voor voorbeelden.

2020-10-29 09:53 UTC, MikeLooijmans requested changes
Zie voor commit tekst voorbeelden:
git log recipes-bsp/fpga/

2020-10-29 10:14 UTC, MikeLooijmans approved these changes

2020-10-29 10:15 UTC, merged